### PR TITLE
Fix python errors

### PR DESCRIPTION
**Pull request by pwplusnick**
This PR will fix python errors I ran into while running python setup.py
test

Note this was with `python --version` outputting `Python 2.7.10`.

### CODE REVIEW

**Comment by pwplusnick** [comment]
I'm closing this as it appears to be oriented towards Python 3.5 rather than 2.7.

**Comment by EricCrosson** [comment]
Hmm, perhaps the real issue should be, doesn't support 2.x?

**Comment by pwplusnick** [comment]
If you are interested in also supporting 2.x then I'm down to help out.

**Comment by EricCrosson** [comment]
I'm around it

**Pull request closed without merging**
